name: Release

on:
    push:
        branches:
            - master

jobs:
    Release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'

            - name: Install dependencies
              run: npm ci

            - name: Generate build code
              run: npm run build --if-present

            - name: Determine next version
              uses: gps/determine-next-version@master
              id: next_version
              with:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Insert Next version to Package.json
              run: sed -i 's/9999.9999.9999/${{steps.next_version.outputs.NEXT_BUILD_VERSION}}/' package.json

            - name: Tag commit
              uses: gps/tag-commit@master
              with:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAG_NAME: v${{steps.next_version.outputs.NEXT_BUILD_VERSION}}
